-- MySQL Script generated by MySQL Workbench
-- 03/10/16 15:37:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CafeNovoHorizonte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CafeNovoHorizonte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CafeNovoHorizonte` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CafeNovoHorizonte` ;

-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Estado` (
  `Id_Estado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nome` CHAR(2) NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Estado`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Cidade` (
  `Id_Clidade` INT NOT NULL COMMENT '',
  `Nome` VARCHAR(100) NOT NULL COMMENT '',
  `Id_Estado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Clidade`)  COMMENT '',
  INDEX `fk_TB_Cidade_TB_Estado1_idx` (`Id_Estado` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Cidade_TB_Estado1`
    FOREIGN KEY (`Id_Estado`)
    REFERENCES `CafeNovoHorizonte`.`TB_Estado` (`Id_Estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Bairro` (
  `Id_Bairro` INT NOT NULL COMMENT '',
  `Nome` VARCHAR(100) NOT NULL COMMENT '',
  `Id_Clidade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Bairro`)  COMMENT '',
  INDEX `fk_TB_Bairro_TB_Cidade1_idx` (`Id_Clidade` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Bairro_TB_Cidade1`
    FOREIGN KEY (`Id_Clidade`)
    REFERENCES `CafeNovoHorizonte`.`TB_Cidade` (`Id_Clidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Rua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Rua` (
  `Id_Rua` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nome` VARCHAR(100) NOT NULL COMMENT '',
  `CEP` CHAR(8) NOT NULL COMMENT '',
  `Id_Bairro` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Rua`)  COMMENT '',
  INDEX `fk_TB_Rua_TB_Bairro1_idx` (`Id_Bairro` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Rua_TB_Bairro1`
    FOREIGN KEY (`Id_Bairro`)
    REFERENCES `CafeNovoHorizonte`.`TB_Bairro` (`Id_Bairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Endereco` (
  `Id_Endereco` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Numero` CHAR(4) NOT NULL COMMENT '',
  `Id_Rua` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Endereco`)  COMMENT '',
  INDEX `fk_TB_Endereco_TB_Rua1_idx` (`Id_Rua` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Endereco_TB_Rua1`
    FOREIGN KEY (`Id_Rua`)
    REFERENCES `CafeNovoHorizonte`.`TB_Rua` (`Id_Rua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Empresa` (
  `Id_Empresa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NomeFantasia` VARCHAR(200) NOT NULL COMMENT '',
  `CPF-CNPJ` VARCHAR(20) NOT NULL COMMENT '',
  `nInscricao` VARCHAR(11) NOT NULL COMMENT '',
  `TipoImposto` SET('Simples Nacional', 'Tributação Normal') NOT NULL DEFAULT 'Simples Nacional' COMMENT '',
  `Email` VARCHAR(100) NOT NULL COMMENT '',
  `Telefone` VARCHAR(12) NOT NULL COMMENT '',
  `Id_Endereco` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Empresa`)  COMMENT '',
  INDEX `fk_TB_Empresa_TB_Endereco1_idx` (`Id_Endereco` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Empresa_TB_Endereco1`
    FOREIGN KEY (`Id_Endereco`)
    REFERENCES `CafeNovoHorizonte`.`TB_Endereco` (`Id_Endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Produto` (
  `Id_Produto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Cod_Produto` INT NOT NULL COMMENT '',
  `Preco` FLOAT NOT NULL COMMENT '',
  `EAN` VARCHAR(45) NOT NULL DEFAULT '-' COMMENT '',
  `EAN_UT` VARCHAR(45) NOT NULL DEFAULT '-' COMMENT '',
  `EX_IPI` VARCHAR(45) NOT NULL DEFAULT '-' COMMENT '',
  `Genero` VARCHAR(100) NOT NULL DEFAULT '-' COMMENT '',
  `NCM` VARCHAR(100) NOT NULL DEFAULT '-' COMMENT '',
  `UndComercial` VARCHAR(100) NOT NULL DEFAULT '-' COMMENT '',
  `Valor_Unidade_Comer` VARCHAR(100) NOT NULL DEFAULT '-' COMMENT '',
  `Und_Tributaria` VARCHAR(100) NOT NULL DEFAULT '-' COMMENT '',
  `Qtd_Tributaria` VARCHAR(100) NOT NULL DEFAULT '-' COMMENT '',
  `ValorUnidadeTributaria` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Produto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Item_venda` (
  `Id_ItemVenda` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Qtd_Produto` INT NOT NULL COMMENT '',
  `Id_Produto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_ItemVenda`, `Id_Produto`)  COMMENT '',
  INDEX `fk_TB_Item_venda_TB_Produto1_idx` (`Id_Produto` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Item_venda_TB_Produto1`
    FOREIGN KEY (`Id_Produto`)
    REFERENCES `CafeNovoHorizonte`.`TB_Produto` (`Id_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_TipoPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_TipoPagamento` (
  `Id_TipoPagamento` INT NOT NULL COMMENT '',
  `TipoPagamento` SET('Á Vista', 'Duplicata') NOT NULL COMMENT '',
  PRIMARY KEY (`Id_TipoPagamento`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_TipoVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_TipoVenda` (
  `Id_TipoVenda` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `TipoVenda` SET('Simplificada', 'Classificação Fiscal') NOT NULL COMMENT '',
  PRIMARY KEY (`Id_TipoVenda`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Venda` (
  `Id_Cliente` INT NOT NULL COMMENT '',
  `Id_ItemVenda` INT NOT NULL COMMENT '',
  `ValorTotal` FLOAT NOT NULL COMMENT '',
  `DataVenda` DATETIME NOT NULL COMMENT '',
  `TB_TipoPagamento_Id_TipoPagamento` INT NOT NULL COMMENT '',
  `TB_TipoVenda_Id_TipoVenda` INT NOT NULL COMMENT '',
  `EmissaoNota` TINYINT(1) NOT NULL COMMENT '',
  INDEX `fk_TB_Cliente_has_TB_Produto_TB_Cliente_idx` (`Id_Cliente` ASC)  COMMENT '',
  INDEX `fk_TB_Item_Venda_TB_Venda1_idx` (`Id_ItemVenda` ASC)  COMMENT '',
  INDEX `fk_TB_Venda_TB_TipoPagamento1_idx` (`TB_TipoPagamento_Id_TipoPagamento` ASC)  COMMENT '',
  INDEX `fk_TB_Venda_TB_TipoVenda1_idx` (`TB_TipoVenda_Id_TipoVenda` ASC)  COMMENT '',
  PRIMARY KEY (`Id_Cliente`, `Id_ItemVenda`)  COMMENT '',
  CONSTRAINT `fk_TB_Cliente_has_TB_Produto_TB_Cliente`
    FOREIGN KEY (`Id_Cliente`)
    REFERENCES `CafeNovoHorizonte`.`TB_Empresa` (`Id_Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Item_Venda_TB_Venda1`
    FOREIGN KEY (`Id_ItemVenda`)
    REFERENCES `CafeNovoHorizonte`.`TB_Item_venda` (`Id_ItemVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Venda_TB_TipoPagamento1`
    FOREIGN KEY (`TB_TipoPagamento_Id_TipoPagamento`)
    REFERENCES `CafeNovoHorizonte`.`TB_TipoPagamento` (`Id_TipoPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Venda_TB_TipoVenda1`
    FOREIGN KEY (`TB_TipoVenda_Id_TipoVenda`)
    REFERENCES `CafeNovoHorizonte`.`TB_TipoVenda` (`Id_TipoVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Fornecedor` (
  `Id_Fornecedor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `TB_Empresa_Id_Empresa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Fornecedor`, `TB_Empresa_Id_Empresa`)  COMMENT '',
  INDEX `fk_TB_Fornecedor_TB_Empresa1_idx` (`TB_Empresa_Id_Empresa` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Fornecedor_TB_Empresa1`
    FOREIGN KEY (`TB_Empresa_Id_Empresa`)
    REFERENCES `CafeNovoHorizonte`.`TB_Empresa` (`Id_Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Cliente` (
  `Id_Cliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `TB_Empresa_Id_Empresa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Cliente`, `TB_Empresa_Id_Empresa`)  COMMENT '',
  INDEX `fk_TB_Cliente_TB_Empresa1_idx` (`TB_Empresa_Id_Empresa` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Cliente_TB_Empresa1`
    FOREIGN KEY (`TB_Empresa_Id_Empresa`)
    REFERENCES `CafeNovoHorizonte`.`TB_Empresa` (`Id_Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Transportadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Transportadora` (
  `Id_Transportadora` INT NOT NULL COMMENT '',
  `TB_Empresa_Id_Empresa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Transportadora`, `TB_Empresa_Id_Empresa`)  COMMENT '',
  INDEX `fk_TB_Transportadora_TB_Empresa1_idx` (`TB_Empresa_Id_Empresa` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Transportadora_TB_Empresa1`
    FOREIGN KEY (`TB_Empresa_Id_Empresa`)
    REFERENCES `CafeNovoHorizonte`.`TB_Empresa` (`Id_Empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Estoque` (
  `Id_Produto` INT NOT NULL COMMENT '',
  `Lote` VARCHAR(45) NOT NULL COMMENT '',
  `DataValidade` DATE NOT NULL COMMENT '',
  `QtdProduto` FLOAT NOT NULL COMMENT '',
  PRIMARY KEY (`Lote`)  COMMENT '',
  INDEX `fk_TB_Estoque_TB_Produto1_idx` (`Id_Produto` ASC)  COMMENT '',
  CONSTRAINT `fk_TB_Estoque_TB_Produto1`
    FOREIGN KEY (`Id_Produto`)
    REFERENCES `CafeNovoHorizonte`.`TB_Produto` (`Id_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CafeNovoHorizonte`.`TB_Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CafeNovoHorizonte`.`TB_Login` (
  `Id_Login` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Login` VARCHAR(50) NOT NULL COMMENT '',
  `Senha` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`Id_Login`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
